const questionData = [
  'Is the superhero that you think male?',
  'Did he gain powers from being bitten by a spider?',
  'Does he have the intelligence to create the technology to give him super powers?',
  'Does he have a shield as a weapon?',
  'Is he a spy?',
  'Does he have green skin?',
  'Does he have the ability to fly?',
  'Did he use a thunder hammer as his weapon?',
  'Does he have magic and other dimensional powers to fight supernatural threats?',
  'Does he have powers that come from cosmic energy',
];

const database = [
  {
    name: 'Spider-Man',
    male: true,
    spider: true,
    technology: false,
    fly: false,
    shield: false,
    spy: false,
    green: false,
    hammer: false,
    wakanda: false,
    magic: false,
    cosmic: false,
    img: 'spider-man',
  },
  {
    name: 'Iron Man',
    male: true,
    spider: false,
    technology: true,
    fly: true,
    shield: false,
    spy: false,
    green: false,
    hammer: false,
    wakanda: false,
    magic: false,
    cosmic: false,
    img: 'iron-man',
  },
  {
    name: 'Captain America',
    male: true,
    spider: false,
    technology: false,
    fly: false,
    shield: true,
    spy: false,
    green: false,
    hammer: false,
    wakanda: false,
    magic: false,
    cosmic: false,
    img: 'captain-america',
  },
  {
    name: 'Black Widow',
    male: false,
    spider: false,
    technology: false,
    fly: false,
    shield: false,
    spy: false,
    green: false,
    hammer: false,
    wakanda: false,
    magic: false,
    cosmic: false,
    img: 'black-widow',
  },
  {
    name: 'Hulk',
    male: true,
    spider: false,
    technology: false,
    fly: false,
    shield: false,
    spy: false,
    green: true,
    hammer: false,
    wakanda: false,
    magic: false,
    cosmic: false,
    img: 'hulk',
  },
  {
    name: 'Thor',
    male: true,
    spider: false,
    technology: false,
    fly: true,
    shield: false,
    spy: false,
    green: false,
    hammer: true,
    wakanda: false,
    magic: false,
    cosmic: false,
    img: 'thor',
  },
  {
    name: 'Dr. Strange',
    male: true,
    spider: false,
    technology: false,
    fly: true,
    shield: false,
    spy: false,
    green: false,
    hammer: false,
    wakanda: false,
    magic: true,
    cosmic: false,
    img: 'dr-strange',
  },
  {
    name: 'Captain Marvel',
    male: false,
    spider: false,
    technology: false,
    fly: true,
    shield: false,
    spy: false,
    green: false,
    hammer: false,
    wakanda: false,
    magic: false,
    cosmic: true,
    img: 'captain-marvel',
  },
];

const property = [
  'male',
  'spider',
  'technology',
  'shield',
  'spy',
  'green',
  'fly',
  'hammer',
  'magic',
  'cosmic',
];
